(()=>{
const p=new URLSearchParams(location.search),demo=p.get('demo')==='1',stage=(p.get('demoStage')||'').toLowerCase(),user=(p.get('demoUser')||'leon').toLowerCase();if(!demo||stage!=='round2')return;
const KEY='lavuq_demo_meeting4_state_v2';
const RECS={
'☕ Ruhig kennenlernen':[['Café am Dom','Kürschnerhof 2, 97070 Würzburg'],['Marktcafé Brandstetter','Marktgasse 3, 97070 Würzburg'],['Caféhaus Brückenbäck','Zeller Straße 2, 97082 Würzburg'],['Café Fred','Herzogenstraße 4, 97070 Würzburg'],['Café Kiess','Kaiserstraße 6, 97070 Würzburg'],['Café Lenz','Spiegelstraße 21, 97070 Würzburg'],['Café Mozart','Theaterstraße 21, 97070 Würzburg'],['Central im Bürgerbräu','Frankfurter Straße 87, 97082 Würzburg']],
'🍽️ Gemeinsam essen':[['Bürgerspital Weinstuben','Theaterstraße 19, 97070 Würzburg'],['Backöfele','Ursulinergasse 2, 97070 Würzburg'],['Wirtshaus am Dom','Paradeplatz 4, 97070 Würzburg'],['Schützenhof','Mainleitenweg 48, 97082 Würzburg'],['Weinstube Maulaffenbäck','Maulhardgasse 9, 97070 Würzburg'],['Sophienbäck','Sophienstraße 6, 97072 Würzburg'],['Restaurant KUNO 1408','Neubaustraße 7, 97070 Würzburg'],['Vier Jahreszeiten','Haugerpfarrgasse 3, 97070 Würzburg'],['Sandwich Club Würzburg','Johanniterplatz 3, 97070 Würzburg']],
'🎳 Gemeinsam etwas machen':[['Bowling Würzburg','Huberstraße 9, 97084 Würzburg'],['Schwarzlichtfabrik Würzburg','Bahnhofplatz 2A, 97070 Würzburg'],['EscapeGames Würzburg','Bahnhofplatz 2, 97070 Würzburg'],['Gamer Würzburg – Die Gameshow','Bahnhofplatz 2A, 97070 Würzburg'],['DAV Kletterzentrum Würzburg','Weißenburgstraße 55, 97082 Würzburg'],['CinemaxX Würzburg','Veitshöchheimer Straße 5A, 97080 Würzburg'],['Museum im Kulturspeicher','Oskar-Laredo-Platz 1, 97080 Würzburg']],
'🌳 Draußen & spazieren':[['Residenz & Hofgarten','Residenzplatz 2, 97070 Würzburg'],['Botanischer Garten','Julius-von-Sachs-Platz 4, 97082 Würzburg'],['Alte Mainbrücke','Alte Mainbrücke, 97070 Würzburg'],['Mainufer / Mainkai','Mainkai, 97070 Würzburg'],['Alter Kranen','Kranenkai, 97070 Würzburg'],['Ringpark','Sanderring, 97070 Würzburg'],['Festung Marienberg','Festung Marienberg, 97082 Würzburg']],
'🏛️ Würzburg entdecken':[['Würzburger Residenz','Residenzplatz 2, 97070 Würzburg'],['Museum im Kulturspeicher','Oskar-Laredo-Platz 1, 97080 Würzburg'],['Festung Marienberg','Festung Marienberg, 97082 Würzburg'],['Mainfranken Theater Würzburg','Theaterstraße 21, 97070 Würzburg'],['Alte Mainbrücke','Alte Mainbrücke, 97070 Würzburg'],['Central im Bürgerbräu','Frankfurter Straße 87, 97082 Würzburg']],
'🌧️ Schlechtwetter':[['Museum im Kulturspeicher','Oskar-Laredo-Platz 1, 97080 Würzburg'],['Bowling Würzburg','Huberstraße 9, 97084 Würzburg'],['Schwarzlichtfabrik Würzburg','Bahnhofplatz 2A, 97070 Würzburg'],['EscapeGames Würzburg','Bahnhofplatz 2, 97070 Würzburg'],['Gamer Würzburg – Die Gameshow','Bahnhofplatz 2A, 97070 Würzburg'],['DAV Kletterzentrum Würzburg','Weißenburgstraße 55, 97082 Würzburg'],['CinemaxX Würzburg','Veitshöchheimer Straße 5A, 97080 Würzburg']]
};
const IDEAS={
'💬 Gesprächsfragen':['Was hat dich diese Woche positiv überrascht?','Welche kleine Sache macht einen Tag für dich sofort besser?','Was würdest du in Würzburg gerne einmal ausprobieren?','Welche Eigenschaft schätzt du an guten Freunden am meisten?','Was war dein schönster spontaner Ausflug?','Wenn du morgen frei hättest: Was würdest du machen?','Welche Musik bringt dich sofort in gute Laune?','Was ist etwas, worüber du stundenlang reden könntest?'],
'🏰 Würzburg-Quiz':['Wie heißt die bekannte Festung oberhalb des Mains?|Festung Marienberg','Welches UNESCO-Welterbe steht am Residenzplatz? |Würzburger Residenz','Wie heißt die historische Brücke mit den Heiligenfiguren? |Alte Mainbrücke','An welchem Fluss liegt Würzburg? |Main','Wie heißt der große Parkring um die Altstadt? |Ringpark','Welcher Garten gehört direkt zur Residenz? |Hofgarten'],
'🤝 Kennenlernquiz':['Wer von euch würde am ehesten spontan einen Wochenendtrip planen?','Wer ist eher Frühaufsteher und wer eher Nachtmensch?','Wer würde am ehesten ein neues Hobby ausprobieren?','Wer kennt vermutlich die meisten Geheimtipps in Würzburg?','Wer ist in Gruppen eher Planer und wer eher spontan?','Wer würde am ehesten den ersten Schritt für ein neues Treffen machen?'],
'🧩 Gruppenrätsel':['Ihr habt drei Schalter und eine Lampe in einem anderen Raum. Ihr dürft den Lampenraum nur einmal betreten. Wie findet ihr den richtigen Schalter?','Was wird nasser, je mehr es trocknet?','Ich habe Städte, aber keine Häuser; Wälder, aber keine Bäume; Wasser, aber keine Fische. Was bin ich?','Zwei Väter und zwei Söhne gehen essen und bestellen nur drei Essen. Wie geht das?','Was gehört dir, wird aber meistens von anderen benutzt?'],
'🎯 Mini-Challenges':['Findet in 3 Minuten drei Gemeinsamkeiten, die nichts mit Arbeit oder Wohnort zu tun haben.','Jede Person nennt einen Würzburg-Ort, den die Gruppe noch nicht gemeinsam besucht hat.','Macht ein Gruppenfoto mit einem typischen Würzburg-Motiv im Hintergrund.','Jede Person empfiehlt der Gruppe eine Aktivität für das nächste Treffen.','Bestellt oder wählt gemeinsam etwas, das noch niemand aus der Gruppe ausprobiert hat.','Findet innerhalb von 5 Minuten den originellsten Namen für eure Vierergruppe.']
};
let used={};
function esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function style(){if(document.getElementById('lavuq-r2x'))return;let s=document.createElement('style');s.id='lavuq-r2x';s.textContent=`.lqsel{width:100%;min-height:48px;border:1px solid #d9d1c4;border-radius:13px;padding:12px 13px;background:#fff;font:inherit;color:#132033;margin-top:8px}.lqaddr{margin-top:9px;padding:11px 12px;border-radius:12px;background:#edf8f1;color:#20543b;font-size:.82rem;font-weight:800}.lqideas{margin-top:14px;padding:14px;border:1px solid #dfd4bf;border-radius:16px;background:#fffaf0}.lqideas h4{margin:0 0 5px}.lqideagrid{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px}.lqibtn{border:1px solid #ddd5c8;background:#fff;border-radius:12px;padding:10px;font:inherit;font-weight:800;text-align:left}.lqibtn.active{background:#041529;color:#fff}.lqideaout{margin-top:10px;padding:13px;border-radius:12px;background:#f3f6f8;line-height:1.5}.lqanswer{margin-top:8px;color:#20543b;font-weight:800}.lqnext{margin-top:9px}.lqsmall{font-size:.78rem;color:#697386;line-height:1.4}@media(max-width:520px){.lqideagrid{grid-template-columns:1fr}}`;document.head.appendChild(s)}
function st(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}}function save(x){localStorage.setItem(KEY,JSON.stringify(x))}function fmt(v){try{return new Date(v).toLocaleString('de-DE',{dateStyle:'short',timeStyle:'short'})}catch{return v}}
function ideaBox(n,locked=false){if(locked)return'';return `<div class="lqideas" data-ideas="${n}"><h4>🎲 LAVUQ-Ideen für euer Treffen</h4><div class="lqsmall">Optional – für lockere Gespräche, Quiz, Rätsel und kleine Gruppen-Challenges.</div><div class="lqideagrid">${Object.keys(IDEAS).map(k=>`<button type="button" class="lqibtn" data-itype="${esc(k)}">${esc(k)}</button>`).join('')}</div><div class="lqideaout hidden" data-iout></div></div>`}
function bindIdeas(root=document){root.querySelectorAll('[data-ideas]').forEach(box=>{if(box.dataset.bound)return;box.dataset.bound='1';let type='';box.querySelectorAll('[data-itype]').forEach(b=>b.onclick=()=>{box.querySelectorAll('[data-itype]').forEach(x=>x.classList.remove('active'));b.classList.add('active');type=b.dataset.itype;showIdea(box,type)});});}
function showIdea(box,type){let arr=IDEAS[type]||[];if(!arr.length)return;used[type]=used[type]||[];let choices=arr.map((_,i)=>i).filter(i=>!used[type].includes(i));if(!choices.length){used[type]=[];choices=arr.map((_,i)=>i)}let idx=choices[Math.floor(Math.random()*choices.length)];used[type].push(idx);let raw=arr[idx],parts=raw.split('|'),q=parts[0].trim(),a=(parts[1]||'').trim(),out=box.querySelector('[data-iout]');out.classList.remove('hidden');out.innerHTML=`<strong>${esc(type)}</strong><div style="margin-top:6px">${esc(q)}</div>${a?`<button type="button" class="btn btn-light lqnext" data-answer>Antwort zeigen</button><div class="lqanswer hidden" data-answerout>${esc(a)}</div>`:''}<button type="button" class="btn btn-primary lqnext" data-next>Nächste Idee</button>`;out.querySelector('[data-answer]')?.addEventListener('click',()=>out.querySelector('[data-answerout]')?.classList.remove('hidden'));out.querySelector('[data-next]').onclick=()=>showIdea(box,type)}
function card(n,title,sub,body='',locked=false){return `<div class="meeting${locked?' meeting-locked':''}" id="meeting-${n}"><div class="meeting-head"><div class="meeting-number">${n}</div><div><strong>${title}</strong><div class="muted">${sub}</div></div></div>${body}${ideaBox(n,locked)}</div>`}
function renderBase(){let list=document.getElementById('meetingList');if(!list)return false;list.innerHTML=card(1,'Treffen 1','Abgeschlossen · Feedback vollständig','<div class="meeting-actions"><div class="status ok compact" style="width:100%">Runde 1 · abgeschlossen ✓</div></div>')+card(2,'Treffen 2','Abgeschlossen · Feedback vollständig','<div class="meeting-actions"><div class="status ok compact" style="width:100%">Runde 1 · abgeschlossen ✓</div></div>')+card(3,'Treffen 3','Abgeschlossen · Feedback vollständig','<div class="meeting-actions"><div class="status ok compact" style="width:100%">Runde 1 · abgeschlossen ✓</div></div>')+`<div style="padding:6px 4px 0;color:#8b6826;font-weight:900;letter-spacing:.08em;text-transform:uppercase;font-size:.78rem">Runde 2 · Treffen 4–6</div>`+card(4,'Treffen 4','Neue Runde gestartet · jetzt Termin planen','<div class="meeting-actions"><button class="btn btn-dark" type="button" data-open>Termin festlegen</button></div><div class="schedule-panel hidden" id="schedule-4"></div>')+card(5,'Treffen 5','Wird nach dem Feedback zu Treffen 4 freigeschaltet.','<div class="meeting-actions"><div class="meeting-lock-note">🔒 Noch gesperrt</div></div>',true)+card(6,'Treffen 6','Wird nach dem Feedback zu Treffen 5 freigeschaltet.','<div class="meeting-actions"><div class="meeting-lock-note">🔒 Noch gesperrt</div></div>',true);bindIdeas(list);document.querySelector('[data-open]')?.addEventListener('click',()=>{let x=document.getElementById('schedule-4');x.classList.toggle('hidden');if(!x.classList.contains('hidden'))renderM4(x)});return true}
function bindRec(panel){let c=panel.querySelector('[data-cat]'),r=panel.querySelector('[data-rec]'),h=panel.querySelector('[data-recval]'),a=panel.querySelector('[data-addr]');c.onchange=()=>{let xs=RECS[c.value]||[];r.innerHTML='<option value="">2. Treffpunkt auswählen</option>'+xs.map((x,i)=>`<option value="${i}">${esc(x[0])} — ${esc(x[1])}</option>`).join('');r.disabled=!xs.length;h.value='';a.classList.add('hidden')};r.onchange=()=>{let x=(RECS[c.value]||[])[Number(r.value)];if(!x)return;h.value=`${x[0]} · ${x[1]}`;a.textContent='📍 '+x[1];a.classList.remove('hidden')}}
function renderM4(panel){let s=st();if(s.proposal){let yes=Object.values(s.votes||{}).filter(Boolean).length,mine=!!(s.votes||{})[user];panel.innerHTML=`<h3>Terminabstimmung · Treffen 4</h3><div class="vote-card"><strong>${yes===4?'Termin verbindlich bestätigt ✓':'Aktueller Vorschlag'}</strong><div style="margin-top:6px">${esc(s.proposal.dateLabel)}<br>${esc(s.proposal.place)}</div><div class="schedule-meta">Zustimmungen: ${yes} von 4</div>${yes<4&&!mine?'<div class="vote-actions"><button class="btn btn-primary" data-yes>Zustimmen</button></div>':''}</div>`;panel.querySelector('[data-yes]')?.addEventListener('click',()=>{let x=st();x.votes=x.votes||{};x.votes[user]=true;save(x);renderM4(panel)});return}
panel.innerHTML=`<h3>Terminabstimmung · Treffen 4</h3><div class="schedule-meta">Vorschlagsrunden: 1 von 5</div><div class="schedule-form"><div class="full"><label>Datum & Uhrzeit</label><input type="datetime-local" data-date min="2026-09-04T00:00" max="2026-10-15T23:59"></div><div class="full"><label>Würzburg-Empfehlungen <span class="muted">(optional)</span></label><select class="lqsel" data-cat><option value="">1. Kategorie auswählen</option>${Object.keys(RECS).map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}</select><select class="lqsel" data-rec disabled><option value="">2. Erst Kategorie auswählen</option></select><div class="lqaddr hidden" data-addr></div><input type="hidden" data-recval></div><div class="full"><label>Eigener Treffpunkt / genaue Idee</label><input type="text" data-place placeholder="Oder eigenen Treffpunkt eintragen"></div><div class="full"><label style="display:flex;gap:10px;align-items:flex-start"><input type="checkbox" data-public style="width:auto;margin-top:3px"> Ich bestätige, dass der Treffpunkt öffentlich ist.</label></div><div class="full"><button class="btn btn-primary" data-send>Vorschlag an die Gruppe senden</button></div></div>`;bindRec(panel);panel.querySelector('[data-send]').onclick=()=>{let d=panel.querySelector('[data-date]').value,pl=(panel.querySelector('[data-place]').value||panel.querySelector('[data-recval]').value||'').trim(),pub=panel.querySelector('[data-public]').checked;if(!d||!pl||!pub){let z=document.getElementById('state');if(z){z.textContent='Bitte Datum, Treffpunkt und die Bestätigung „öffentlicher Treffpunkt“ ausfüllen.';z.className='status err'}return}let x={proposal:{date:d,dateLabel:fmt(d),place:pl},votes:{leon:false,anna:false,sophie:false,daniel:false}};x.votes[user]=true;save(x);renderM4(panel)}}
function start(){style();let t=0,i=setInterval(()=>{t++;if(renderBase()||t>40)clearInterval(i)},150)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();