const BASE_ID="apphnIBhuAbmMTUtY";
const GROUPS="tblF8peAAJGjwfKab", MEMBERS="tbl4QX0NIB3tUKtF4", APPLICANTS="tblzLtbR5Yh4nR5aQ", CHAT="tblU0wjh9fIXwBu8l", MEETINGS="tblHoWMR2fkeLDkec", FEEDBACK="tblLyjFTdr1MziUgj", SAFETY="tblC7cdGwA0Aa1f7U";
const F={
 groupCode:"fldCb3rBz4kTWzQLx",groupStatus:"fldpizdbKv9LGxMDa",
 memberGroup:"fldMUYzXykTpV0j2x",memberApplicant:"fldcV8kd6KF7zdScE",memberStatus:"fldBS2hoKQX0Rr1aX",inviteStatus:"fldUmjMa2j7MLG5RA",inviteToken:"fldbbkqZ7VRvtbzB0",
 applicantName:"fldPPnyiAKpIXnawY",applicantCode:"fld5MVt7Qs57DZ0G3",
 chatId:"fldbf1HRUwDqHdjmW",chatGroup:"fldBW1uipqZMHkIf0",chatMember:"fldbgTxIrBHp9fY7L",chatMessage:"fldYhYzB22IIqMycq",chatSent:"fld2h9pAXkNzQvkA7",chatSystem:"fldXJdZUoXJrfQAaU",
 meetingGroup:"fld0Zpt6q0OO9RmTt",meetingAttempt:"fld1Wu66kB9akZVje",meetingDate:"fldGIDne7S1fY997i",meetingPlace:"fld7gEEQzLn3RMxoq",meetingStatus:"fldAZyz79cEpcGweE",meetingAgreed:"flddvVn0fyhznL454",
 feedbackMeeting:"fldaykTvzKmCqn9MO",feedbackApplicant:"fldkOnMXpqlnNjs1b",feedbackLink:"fldwHXctCJcj9eHYE",feedbackValid:"fldszL9Bjcsk5UDFD",feedbackSubmitted:"fld5uezt0LJJdtd29",
 safetyId:"fldlj8v2ZYFMTrfrG",safetyGroupCode:"fldFjwvVdBPFdkV8h",safetyApplicantCode:"fldOdkat9gJYhWooY",safetyReported:"fldtnFSmIYs2aNK1J",safetyUrgency:"fldp38xY6Va0JPdZU",safetyStatus:"fldQjsDIJR6LZuAER",safetyDescription:"fldoejD40xDN3qEXi",safetyPaused:"fld8lTMOOhmECdrm7",safetyGroup:"fld3nIBgc1GCzTUMM",safetyAcute:"fldC3bsflOAIOWajK",safetyReviewed:"fldJuTg1QLmzqXmVR",safetyNotified:"fldzCxnyozu3xwd84"
};
function headers(env){return{Authorization:`Bearer ${env.AIRTABLE_TOKEN}`,"Content-Type":"application/json"};}
function text(v){if(v==null)return"";if(typeof v==="object"&&!Array.isArray(v)&&v.name)return String(v.name).trim();return String(v).trim();}
function links(v){return Array.isArray(v)?v.map(x=>typeof x==="string"?x:x?.id).filter(Boolean):[];}
async function get(env,table,id){const r=await fetch(`https://api.airtable.com/v0/${BASE_ID}/${table}/${id}?returnFieldsByFieldId=true`,{headers:headers(env)});if(!r.ok)throw new Error(`${table} GET ${r.status}`);return r.json();}
async function list(env,table){let out=[],offset="";do{const q=new URLSearchParams({pageSize:"100",returnFieldsByFieldId:"true"});if(offset)q.set("offset",offset);const r=await fetch(`https://api.airtable.com/v0/${BASE_ID}/${table}?${q}`,{headers:headers(env)});if(!r.ok)throw new Error(`${table} LIST ${r.status}`);const j=await r.json();out.push(...(j.records||[]));offset=String(j.offset||"");}while(offset);return out;}
async function create(env,table,fields){const r=await fetch(`https://api.airtable.com/v0/${BASE_ID}/${table}`,{method:"POST",headers:headers(env),body:JSON.stringify({fields})});if(!r.ok)throw new Error(`${table} POST ${r.status}`);return r.json();}
function accepted(m){return text(m?.fields?.[F.memberStatus])==="Aktiv"&&text(m?.fields?.[F.inviteStatus])==="Angenommen";}
async function auth(env,memberId,token){if(!/^rec[A-Za-z0-9]{14}$/.test(memberId)||!token)return null;const member=await get(env,MEMBERS,memberId);if(text(member?.fields?.[F.inviteToken])!==token||!accepted(member))return null;const groupId=links(member?.fields?.[F.memberGroup])[0],applicantId=links(member?.fields?.[F.memberApplicant])[0];if(!groupId||!applicantId)return null;return{member,groupId,applicantId};}
async function groupPeople(env,groupId){const [members,applicants]=await Promise.all([list(env,MEMBERS),list(env,APPLICANTS)]);const apps=new Map(applicants.map(a=>[a.id,a]));return members.filter(m=>links(m?.fields?.[F.memberGroup]).includes(groupId)&&accepted(m)).map(m=>{const aid=links(m?.fields?.[F.memberApplicant])[0];return{memberId:m.id,name:text(apps.get(aid)?.fields?.[F.applicantName])||"Teilnehmer"};});}
function safeMessage(v,max=1200){return String(v||"").replace(/\r/g,"").trim().slice(0,max);}
function future(v){const d=new Date(v);return Number.isFinite(d.getTime())&&d.getTime()>Date.now();}
export async function handleMemberAreaStatus(env,input={}){const a=await auth(env,String(input.memberId||""),String(input.token||""));if(!a)return{ok:false,status:403,code:"INVALID_MEMBER_ACCESS"};const [group,people,meetings,feedback]=await Promise.all([get(env,GROUPS,a.groupId),groupPeople(env,a.groupId),list(env,MEETINGS),list(env,FEEDBACK)]);const me=people.find(p=>p.memberId===a.member.id);const groupMeetings=meetings.filter(m=>links(m?.fields?.[F.meetingGroup]).includes(a.groupId)).sort((x,y)=>Number(x?.fields?.[F.meetingAttempt]||0)-Number(y?.fields?.[F.meetingAttempt]||0));const meetingIds=new Set(groupMeetings.map(m=>m.id));const myFeedback=feedback.filter(f=>links(f?.fields?.[F.feedbackApplicant]).includes(a.applicantId)&&links(f?.fields?.[F.feedbackMeeting]).some(id=>meetingIds.has(id)));const meetingView=[1,2,3].map(attempt=>{const m=groupMeetings.find(x=>Number(x?.fields?.[F.meetingAttempt]||0)===attempt);const fb=m?myFeedback.find(x=>links(x?.fields?.[F.feedbackMeeting]).includes(m.id)):null;const feedbackLink=fb&&!fb?.fields?.[F.feedbackSubmitted]&&future(fb?.fields?.[F.feedbackValid])?text(fb?.fields?.[F.feedbackLink]):"";return{attempt,scheduled:Boolean(m),dateTime:m?.fields?.[F.meetingDate]||null,place:text(m?.fields?.[F.meetingPlace]),status:text(m?.fields?.[F.meetingStatus]),agreed:m?.fields?.[F.meetingAgreed]===true,feedbackAvailable:Boolean(feedbackLink),feedbackLink:feedbackLink||null,feedbackSubmitted:Boolean(fb?.fields?.[F.feedbackSubmitted])};});return{ok:true,status:200,member:{name:me?.name||"Teilnehmer"},group:{id:a.groupId,code:text(group?.fields?.[F.groupCode]),status:text(group?.fields?.[F.groupStatus]),memberCount:people.length,members:people.map(p=>({name:p.name,isMe:p.memberId===a.member.id}))},meetings:meetingView,features:{groupChat:true,meetingPlanning:true,feedback:true,safetyReport:true,privateContactSharing:false},piiExposedInResponse:false};}
export async function handleMemberChatList(env,input={}){const a=await auth(env,String(input.memberId||""),String(input.token||""));if(!a)return{ok:false,status:403,code:"INVALID_MEMBER_ACCESS"};const [rows,people]=await Promise.all([list(env,CHAT),groupPeople(env,a.groupId)]);const names=new Map(people.map(p=>[p.memberId,p.name]));const messages=rows.filter(r=>links(r?.fields?.[F.chatGroup]).includes(a.groupId)).sort((x,y)=>new Date(x?.fields?.[F.chatSent]||0)-new Date(y?.fields?.[F.chatSent]||0)).slice(-100).map(r=>{const mid=links(r?.fields?.[F.chatMember])[0];return{id:r.id,sender:names.get(mid)||"LAVUQ",isMe:mid===a.member.id,message:text(r?.fields?.[F.chatMessage]),sentAt:r?.fields?.[F.chatSent]||null,system:r?.fields?.[F.chatSystem]===true};});return{ok:true,status:200,messages};}
export async function handleMemberChatSend(env,input={}){const a=await auth(env,String(input.memberId||""),String(input.token||""));if(!a)return{ok:false,status:403,code:"INVALID_MEMBER_ACCESS"};const message=safeMessage(input.message);if(message.length<1)return{ok:false,status:400,code:"MESSAGE_REQUIRED"};const now=new Date().toISOString();const id=`CHAT-${Date.now().toString(36)}-${crypto.randomUUID().slice(0,8)}`;await create(env,CHAT,{[F.chatId]:id,[F.chatGroup]:[a.groupId],[F.chatMember]:[a.member.id],[F.chatMessage]:message,[F.chatSent]:now,[F.chatSystem]:false});return{ok:true,status:200,state:"MESSAGE_SENT",sentAt:now};}
export async function handleMemberSafetyReport(env,input={}){const a=await auth(env,String(input.memberId||""),String(input.token||""));if(!a)return{ok:false,status:403,code:"INVALID_MEMBER_ACCESS"};const description=safeMessage(input.description,3000),urgency=String(input.urgency||"Normal");if(description.length<10)return{ok:false,status:400,code:"SAFETY_DESCRIPTION_REQUIRED"};if(!["Normal","Dringend","Akute Gefahr"].includes(urgency))return{ok:false,status:400,code:"INVALID_URGENCY"};const [group,applicant]=await Promise.all([get(env,GROUPS,a.groupId),get(env,APPLICANTS,a.applicantId)]);const now=new Date().toISOString(),id=`SAFE-${Date.now().toString(36)}-${crypto.randomUUID().slice(0,8)}`;await create(env,SAFETY,{[F.safetyId]:id,[F.safetyGroupCode]:text(group?.fields?.[F.groupCode])||a.groupId,[F.safetyApplicantCode]:text(applicant?.fields?.[F.applicantCode])||a.applicantId,[F.safetyReported]:now,[F.safetyUrgency]:urgency,[F.safetyStatus]:"Neu",[F.safetyDescription]:description,[F.safetyPaused]:true,[F.safetyGroup]:[a.groupId],[F.safetyAcute]:urgency==="Akute Gefahr",[F.safetyReviewed]:false,[F.safetyNotified]:false});return{ok:true,status:200,state:"SAFETY_REPORT_CREATED",automationsPaused:true,acuteDanger:urgency==="Akute Gefahr"};}
