const BASE_ID="apphnIBhuAbmMTUtY";
const GROUPS="tblF8peAAJGjwfKab", MEMBERS="tbl4QX0NIB3tUKtF4", APPLICANTS="tblzLtbR5Yh4nR5aQ", CHAT="tblU0wjh9fIXwBu8l";
const F={
 groupCode:"fldCb3rBz4kTWzQLx",groupStatus:"fldpizdbKv9LGxMDa",
 memberGroup:"fldMUYzXykTpV0j2x",memberApplicant:"fldcV8kd6KF7zdScE",memberStatus:"fldBS2hoKQX0Rr1aX",inviteStatus:"fldUmjMa2j7MLG5RA",inviteToken:"fldbbkqZ7VRvtbzB0",
 applicantName:"fldPPnyiAKpIXnawY",
 chatId:"fldbf1HRUwDqHdjmW",chatGroup:"fldBW1uipqZMHkIf0",chatMember:"fldbgTxIrBHp9fY7L",chatMessage:"fldYhYzB22IIqMycq",chatSent:"fld2h9pAXkNzQvkA7",chatSystem:"fldXJdZUoXJrfQAaU"
};
function headers(env){return{Authorization:`Bearer ${env.AIRTABLE_TOKEN}`,"Content-Type":"application/json"};}
function text(v){if(v==null)return"";if(typeof v==="object"&&!Array.isArray(v)&&v.name)return String(v.name).trim();return String(v).trim();}
function links(v){return Array.isArray(v)?v.map(x=>typeof x==="string"?x:x?.id).filter(Boolean):[];}
async function get(env,table,id){const r=await fetch(`https://api.airtable.com/v0/${BASE_ID}/${table}/${id}?returnFieldsByFieldId=true`,{headers:headers(env)});if(!r.ok)throw new Error(`${table} GET ${r.status}`);return r.json();}
async function list(env,table){let out=[],offset="";do{const q=new URLSearchParams({pageSize:"100",returnFieldsByFieldId:"true"});if(offset)q.set("offset",offset);const r=await fetch(`https://api.airtable.com/v0/${BASE_ID}/${table}?${q}`,{headers:headers(env)});if(!r.ok)throw new Error(`${table} LIST ${r.status}`);const j=await r.json();out.push(...(j.records||[]));offset=String(j.offset||"");}while(offset);return out;}
async function create(env,table,fields){const r=await fetch(`https://api.airtable.com/v0/${BASE_ID}/${table}`,{method:"POST",headers:headers(env),body:JSON.stringify({fields})});if(!r.ok)throw new Error(`${table} POST ${r.status}`);return r.json();}
function accepted(m){return text(m?.fields?.[F.memberStatus])==="Aktiv"&&text(m?.fields?.[F.inviteStatus])==="Angenommen";}
async function auth(env,memberId,token){if(!/^rec[A-Za-z0-9]{14}$/.test(memberId)||!token)return null;const member=await get(env,MEMBERS,memberId);if(text(member?.fields?.[F.inviteToken])!==token||!accepted(member))return null;const groupId=links(member?.fields?.[F.memberGroup])[0];if(!groupId)return null;return{member,groupId};}
async function groupPeople(env,groupId){const [members,applicants]=await Promise.all([list(env,MEMBERS),list(env,APPLICANTS)]);const apps=new Map(applicants.map(a=>[a.id,a]));return members.filter(m=>links(m?.fields?.[F.memberGroup]).includes(groupId)&&accepted(m)).map(m=>{const aid=links(m?.fields?.[F.memberApplicant])[0];return{memberId:m.id,name:text(apps.get(aid)?.fields?.[F.applicantName])||"Teilnehmer"};});}
function safeMessage(v){return String(v||"").replace(/\r/g,"").trim().slice(0,1200);}
export async function handleMemberAreaStatus(env,input={}){const a=await auth(env,String(input.memberId||""),String(input.token||""));if(!a)return{ok:false,status:403,code:"INVALID_MEMBER_ACCESS"};const [group,people]=await Promise.all([get(env,GROUPS,a.groupId),groupPeople(env,a.groupId)]);const me=people.find(p=>p.memberId===a.member.id);return{ok:true,status:200,member:{name:me?.name||"Teilnehmer"},group:{id:a.groupId,code:text(group?.fields?.[F.groupCode]),status:text(group?.fields?.[F.groupStatus]),memberCount:people.length,members:people.map(p=>({name:p.name,isMe:p.memberId===a.member.id}))},features:{groupChat:true,meetingPlanning:true,privateContactSharing:false},piiExposedInResponse:false};}
export async function handleMemberChatList(env,input={}){const a=await auth(env,String(input.memberId||""),String(input.token||""));if(!a)return{ok:false,status:403,code:"INVALID_MEMBER_ACCESS"};const [rows,people]=await Promise.all([list(env,CHAT),groupPeople(env,a.groupId)]);const names=new Map(people.map(p=>[p.memberId,p.name]));const messages=rows.filter(r=>links(r?.fields?.[F.chatGroup]).includes(a.groupId)).sort((x,y)=>new Date(x?.fields?.[F.chatSent]||0)-new Date(y?.fields?.[F.chatSent]||0)).slice(-100).map(r=>{const mid=links(r?.fields?.[F.chatMember])[0];return{id:r.id,sender:names.get(mid)||"LAVUQ",isMe:mid===a.member.id,message:text(r?.fields?.[F.chatMessage]),sentAt:r?.fields?.[F.chatSent]||null,system:r?.fields?.[F.chatSystem]===true};});return{ok:true,status:200,messages};}
export async function handleMemberChatSend(env,input={}){const a=await auth(env,String(input.memberId||""),String(input.token||""));if(!a)return{ok:false,status:403,code:"INVALID_MEMBER_ACCESS"};const message=safeMessage(input.message);if(message.length<1)return{ok:false,status:400,code:"MESSAGE_REQUIRED"};if(message.length>1200)return{ok:false,status:400,code:"MESSAGE_TOO_LONG"};const now=new Date().toISOString();const id=`CHAT-${Date.now().toString(36)}-${crypto.randomUUID().slice(0,8)}`;await create(env,CHAT,{[F.chatId]:id,[F.chatGroup]:[a.groupId],[F.chatMember]:[a.member.id],[F.chatMessage]:message,[F.chatSent]:now,[F.chatSystem]:false});return{ok:true,status:200,state:"MESSAGE_SENT",sentAt:now};}
